[project]
dependencies = ["cachetools", "geopy", "requests", "tenacity", "xmltodict"]
name = "osm-addr-bot"
requires-python = "~=3.13"
version = "0.0.0"

[tool.uv]
package = false
python-downloads = "never"
python-preference = "only-system"

[tool.setuptools]
packages = ["."]
